#! /bin/sh

# $Id: getjava 6644 2007-06-29 20:47:39Z jgehlbach $

#
# Get JAVA_HOME and derive PATH
#

if [ -z "$JAVA_HOME" ]; then
    for dir in /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-1.5.0-sun
    do
        if [ -d "$dir" -a -f "$dir/lib/tools.jar" ]; then
            JAVA_HOME="$dir"
            break
        fi
    done

    if [ -z "$JAVA_HOME" ]; then
        echo "You need to set a valid JAVA_HOME in /etc/default/$NAME" >&2
        exit 1
    fi
fi
PATH=${JAVA_HOME}/bin:$PATH

case "$1" in
	"JAVA_HOME")
		echo "$JAVA_HOME"
		;;
	"PATH")
		echo "$PATH"
		;;
	*)
		echo "You must specify either JAVA_HOME or PATH as the sole argument."
		exit 1
		;;
esac

