#! /bin/sh

# $Id: getjava 6644 2007-06-29 20:47:39Z jgehlbach $

if [ -z "$JAVA_HOME" ]; then
    for dir in /usr/lib/jvm/*5* /usr/lib/jvm/*6* /usr/lib/jvm/*7* /usr/lib/jvm/*
    do
        if [ -d "$dir" ] && [ -f "$dir/lib/tools.jar" ]; then
            JAVA_HOME="$dir"
            break
        fi
    done

    if [ -z "$JAVA_HOME" ]; then
        echo "Could not find the jvm, please set JAVA_HOME" >&2
        exit 1
    fi
fi

echo "$JAVA_HOME"
