#!/bin/sh -

top="`pwd`"
target="$top/target"
lib="$target/lib"

arch="`uname -p`"
prototype="prototype.$arch"

if [ ! -f $prototype ]; then
    echo "$0: $prototype does not exist.  this architecture ($arch) does not seem to be supported." >&2
    exit 1
fi

rm -rf "$target"

mkdir "$target" || exit 1

if [ -f ../Makefile ]; then
    ( cd .. && make distclean ) || exit 1
fi

( cd .. && ./configure --with-jvm-arch=32 --prefix="$target" --libdir="$lib/32" ) || exit 1
( cd .. && make install ) || exit 1

( cd .. && make distclean ) || exit 1

( cd .. && ./configure --with-jvm-arch=64 --prefix="$target" --libdir="$lib/64" ) || exit 1
( cd .. && make install ) || exit 1

( cd .. && make solaris/pkginfo ) || exit 1

find $target -name '*.la' -print | xargs rm || exit 1

pkgmk -o -r `pwd` -f $prototype || exit 1

pkgtrans /var/spool/pkg $top/jicmp.pkg NMSjicmp || exit 1
